### ISSUE TITLE
Migrate off BuildKite

### ISSUE THREAD

**Issue by benbz** [matrix-org/synapse-spamcheck-badlist#26]
We're ramping down our BuildKite usage and this project is one of the few left on it. How much work would it be to migrate to GH Actions/similar so that CI was under your span of control?

**Comment by DMRobertson** [comment]
Difficult to say---can't see any BK config in this repo or in [the pipelines repo](https://github.com/matrix-org/pipelines). Looks like the tests directory is well documented though---don't see any reason why we can't commit to before EOY.

**Comment by benbz** [comment]
![image](https://user-images.githubusercontent.com/1325121/199033999-75ac6209-77fc-4537-a986-0da50873dfd4.png)
![image](https://user-images.githubusercontent.com/1325121/199034053-2dcd5f05-6239-43bd-8df5-796b7dd5f51a.png)
is what I can find

**Comment by DMRobertson** [comment]
(Odd. I couldn't see that before---but deleting my BK account and re-logging in via SSO has fixed that)

**Comment by DMRobertson** [comment]
I was able to delete the pipeline for this on buildkit, I think---though I did get an error message warning me that it couldn't be deleted while a build was in progress. In any case, I can't see it at https://buildkite.com/matrix-dot-org any more.
