### ISSUE TITLE
calls `treq.Response.collect` without logcontext wrapping

### ISSUE THREAD

**Issue by richvdh** [matrix-org/synapse-spamcheck-badlist#6]
[`check_event_for_spam`](https://github.com/matrix-org/synapse-spamcheck-badlist/blob/main/synapse_spamcheck_badlist/bad_list_filter.py#L174) calls `await response.collect(...)`. 

`treq.Response.collect` is non-synapse code which returns a Deferred; accordingly you need to call `make_deferred_yieldable` on the Deferred before it is safe to `await` from inside synapse code (otherwise you will leak logcontexts).

**Comment by Yoric** [comment]
The entire method has been rewritten and `await response.collect(...)` has disappeared at some point.
